const categoryTopics = {
  Frontend: [
    "React",
    "JavaScript",
    "TypeScript",
    "CSS",
    "HTML",
    "Next.js",
    "Angular",
    "Vue.js",
    "Svelte",
  ],

  Backend: [
    "Node.js",
    "Python",
    "Express.js",
    "Java",
    "Spring Boot",
    "NestJS",
    "Django",
    "FastAPI",
    "C#",
    ".NET",
    "Go",
    "PHP",
    "Laravel",
    "Ruby",
  ],

  Database: [
    "SQL",
    "PostgreSQL",
    "MongoDB",
    "MySQL",
    "Redis",
    "SQLite",
  ],

  "DevOps & Cloud": [
    "Git",
    "GitHub",
    "Linux",
    "Docker",
    "Kubernetes",
    "AWS",
    "GitHub Actions",
    "Terraform",
    "Nginx",
    "Microsoft Azure",
    "Google Cloud",
    "GitLab",
    "Jenkins",
    "Ansible",
  ],

  "System Design": [
    "Distributed Systems",
    "Microservices",
    "REST API",
    "Caching",
    "Load Balancing",
    "WebSockets",
    "Kafka",
    "GraphQL",
    "RabbitMQ",
    "CDN",
    "Elasticsearch",
    "Serverless",
    "Redis",
    "Nginx",
  ],

  "AI / ML": [
    "Python",
    "Machine Learning",
    "Deep Learning",
    "PyTorch",
    "TensorFlow",
    "Transformers",
    "LLMs",
    "Generative AI",
    "RAG",
    "AI Agents",
    "NLP",
    "Computer Vision",
    "Hugging Face",
    "LangChain",
    "NumPy",
    "Pandas",
    "Scikit-learn",
    "Keras",
    "LlamaIndex",
  ],

  "CS Fundamentals": [
    "Data Structures",
    "Algorithms",
    "OOP",
    "Operating Systems",
    "Computer Networks",
    "DBMS",
    "Concurrency",
    "Distributed Systems",
    "Computer Architecture",
    "Software Engineering",
    "Compiler Design",
  ],

   "Cybersecurity": [
    "Web Security",
    "OWASP",
    "Authentication",
    "Authorization",
    "OAuth",
    "JWT",
    "HTTPS",
    "TLS",
    "CORS",
    "CSRF",
    "XSS",
    "SQL Injection",
    "Encryption",
    "Network Security",
  ],

  "Testing": [
    "Jest",
    "Vitest",
    "Playwright",
    "Cypress",
    "Selenium",
    "React Testing Library",
    "PyTest",
    "JUnit",
    "Postman",
    "Supertest",
    "Unit Testing",
    "Integration Testing",
    "End-to-End Testing",
    "Load Testing",
  ],

  "Mobile Development": [
    "React Native",
    "Flutter",
    "Android",
    "Kotlin",
    "Java",
    "iOS",
    "Swift",
    "SwiftUI",
    "Expo",
    "Jetpack Compose",
  ],
};

export default categoryTopics