const questionBanks = {
  // =========================
  // FRONTEND
  // =========================

  React: [
    "Components",
    "JSX",
    "Props",
    "State",
    "Event Handling",
    "Conditional Rendering",
    "List Rendering",
    "Keys",
    "Forms",
    "Controlled Components",
    "Uncontrolled Components",
    "useState",
    "useEffect",
    "useRef",
    "useMemo",
    "useCallback",
    "useContext",
    "Custom Hooks",
    "Component Lifecycle",
    "Lifting State Up",
    "Prop Drilling",
    "Context API",
    "React Router",
    "Performance Optimization",
    "Error Boundaries",
  ],

  JavaScript: [
    "Variables",
    "Data Types",
    "Operators",
    "Type Coercion",
    "Conditionals",
    "Loops",
    "Functions",
    "Arrow Functions",
    "Scope",
    "Hoisting",
    "Closures",
    "this Keyword",
    "Objects",
    "Arrays",
    "Destructuring",
    "Spread and Rest Operators",
    "Template Literals",
    "Array Methods",
    "Higher-Order Functions",
    "Promises",
    "Async and Await",
    "Event Loop",
    "DOM Manipulation",
    "Event Handling",
    "ES Modules",
  ],

  CSS: [
    "Selectors",
    "Specificity",
    "Cascade",
    "Inheritance",
    "Box Model",
    "Display",
    "Positioning",
    "Z-Index",
    "Overflow",
    "Flexbox",
    "Grid",
    "Responsive Design",
    "Media Queries",
    "Units",
    "Colors",
    "Typography",
    "Pseudo-Classes",
    "Pseudo-Elements",
    "Transitions",
    "Transforms",
    "Animations",
    "Variables",
    "Functions",
    "BEM",
    "Accessibility",
  ],

  TypeScript: [
    "Type Annotations",
    "Type Inference",
    "Primitive Types",
    "Arrays and Tuples",
    "Enums",
    "Union Types",
    "Intersection Types",
    "Literal Types",
    "Type Aliases",
    "Interfaces",
    "Interface Extension",
    "Optional Properties",
    "Readonly Properties",
    "Function Types",
    "Optional Parameters",
    "Generics",
    "Generic Constraints",
    "Type Guards",
    "Type Assertions",
    "Keyof Operator",
    "Typeof Operator",
    "Utility Types",
    "Mapped Types",
    "Conditional Types",
    "Modules",
  ],

  HTML: [
    "Document Structure",
    "DOCTYPE",
    "HTML Elements",
    "HTML Attributes",
    "Semantic Elements",
    "Headings",
    "Paragraphs",
    "Text Formatting",
    "Links",
    "Images",
    "Lists",
    "Tables",
    "Forms",
    "Input Types",
    "Form Validation",
    "Buttons",
    "Select and Option",
    "Audio and Video",
    "Iframes",
    "Canvas",
    "SVG",
    "Meta Tags",
    "Accessibility",
    "ARIA",
    "SEO",
  ],

  "Next.js": [
    "App Router",
    "Pages Router",
    "File-Based Routing",
    "Dynamic Routes",
    "Nested Routes",
    "Route Groups",
    "Layouts",
    "Loading UI",
    "Error Handling",
    "Server Components",
    "Client Components",
    "Server Actions",
    "Data Fetching",
    "Caching",
    "Revalidation",
    "Static Rendering",
    "Dynamic Rendering",
    "Incremental Static Regeneration",
    "Middleware",
    "Route Handlers",
    "API Routes",
    "Metadata",
    "Image Optimization",
    "Authentication",
    "Performance Optimization",
  ],

  Angular: [
    "Components",
    "Templates",
    "Data Binding",
    "Interpolation",
    "Property Binding",
    "Event Binding",
    "Two-Way Binding",
    "Directives",
    "Structural Directives",
    "Attribute Directives",
    "Pipes",
    "Services",
    "Dependency Injection",
    "Modules",
    "Standalone Components",
    "Routing",
    "Route Parameters",
    "Guards",
    "Reactive Forms",
    "Template-Driven Forms",
    "Form Validation",
    "Observables",
    "RxJS",
    "HTTP Client",
  ],

  "Vue.js": [
    "Components",
    "Templates",
    "Directives",
    "Data Binding",
    "Event Handling",
    "Computed Properties",
    "Watchers",
    "Conditional Rendering",
    "List Rendering",
    "Props",
    "Emits",
    "Slots",
    "Component Lifecycle",
    "Composition API",
    "Options API",
    "Reactive State",
    "ref",
    "reactive",
    "computed",
    "watch",
    "Composables",
    "Vue Router",
    "Pinia",
    "Forms",
    "Transitions",
  ],

  Svelte: [
    "Components",
    "Svelte Syntax",
    "Reactive Statements",
    "Reactive Declarations",
    "Props",
    "Event Handling",
    "Conditional Rendering",
    "List Rendering",
    "Bindings",
    "Class Directives",
    "Style Directives",
    "Slots",
    "Component Lifecycle",
    "Stores",
    "Writable Stores",
    "Derived Stores",
    "Context API",
    "Actions",
    "Transitions",
    "Animations",
    "Motion",
    "SvelteKit",
    "Routing",
    "Server-Side Rendering",
    "Form Actions",
  ],

  // =========================
  // BACKEND
  // =========================

  "Node.js": [
    "Runtime Architecture",
    "V8 Engine",
    "Event Loop",
    "Non-Blocking I/O",
    "Asynchronous Programming",
    "Callbacks",
    "Promises",
    "Async/Await",
    "Event Emitters",
    "Streams",
    "Buffers",
    "File System",
    "HTTP Module",
    "Process Object",
    "Environment Variables",
    "CommonJS Modules",
    "ES Modules",
    "NPM",
    "Package Management",
    "Middleware",
    "Error Handling",
    "Child Processes",
    "Worker Threads",
    "Clustering",
    "Security",
  ],

  "Express.js": [
    "Application Setup",
    "Routing",
    "Route Parameters",
    "Query Parameters",
    "Request Object",
    "Response Object",
    "Middleware",
    "Application Middleware",
    "Router Middleware",
    "Error Handling",
    "Error Middleware",
    "Request Validation",
    "HTTP Methods",
    "Route Handlers",
    "Nested Routers",
    "Static Files",
    "CORS",
    "Cookies",
    "Sessions",
    "Authentication",
    "Authorization",
    "API Development",
    "Rate Limiting",
    "Security",
    "Testing",
  ],

  NestJS: [
    "Modules",
    "Controllers",
    "Providers",
    "Services",
    "Dependency Injection",
    "Decorators",
    "Middleware",
    "Guards",
    "Interceptors",
    "Pipes",
    "Exception Filters",
    "Request Lifecycle",
    "Routing",
    "DTOs",
    "Request Validation",
    "Class Validators",
    "Custom Decorators",
    "Configuration",
    "Environment Variables",
    "Authentication",
    "Authorization",
    "JWT",
    "Database Integration",
    "Testing",
    "Microservices",
  ],

  Python: [
    "Python Syntax",
    "Variables",
    "Data Types",
    "Type Conversion",
    "Operators",
    "Conditional Statements",
    "Loops",
    "Functions",
    "Function Arguments",
    "Lambda Functions",
    "Scope",
    "Recursion",
    "Lists",
    "Tuples",
    "Sets",
    "Dictionaries",
    "List Comprehensions",
    "Dictionary Comprehensions",
    "String Manipulation",
    "Exception Handling",
    "File Handling",
    "Modules and Packages",
    "Object-Oriented Programming",
    "Decorators",
    "Generators",
  ],

  Java: [
    "Variables",
    "Data Types",
    "Operators",
    "Type Casting",
    "Conditional Statements",
    "Loops",
    "Methods",
    "Method Overloading",
    "Classes and Objects",
    "Constructors",
    "Inheritance",
    "Polymorphism",
    "Abstraction",
    "Encapsulation",
    "Interfaces",
    "Abstract Classes",
    "Access Modifiers",
    "Static Keyword",
    "Final Keyword",
    "Exception Handling",
    "Collections Framework",
    "Generics",
    "Multithreading",
    "Streams",
    "Lambda Expressions",
  ],

  "Spring Boot": [
    "Project Structure",
    "Application Configuration",
    "Spring Boot Starters",
    "Dependency Injection",
    "Inversion of Control",
    "Beans",
    "Component Scanning",
    "Annotations",
    "Controllers",
    "REST APIs",
    "Request Mapping",
    "Request Parameters",
    "Request Body",
    "Response Entities",
    "Exception Handling",
    "Validation",
    "Profiles",
    "Configuration Properties",
    "Spring Data JPA",
    "Entities",
    "Repositories",
    "Database Relationships",
    "Transactions",
    "Spring Security",
    "Actuator",
  ],

  "C#": [
    "Variables",
    "Data Types",
    "Operators",
    "Type Casting",
    "Conditional Statements",
    "Loops",
    "Methods",
    "Method Overloading",
    "Classes and Objects",
    "Constructors",
    "Inheritance",
    "Polymorphism",
    "Encapsulation",
    "Abstraction",
    "Interfaces",
    "Abstract Classes",
    "Properties",
    "Access Modifiers",
    "Static Members",
    "Exception Handling",
    "Collections",
    "Generics",
    "Delegates",
    "LINQ",
    "Async and Await",
  ],

  ".NET": [
    "Runtime",
    "CLR",
    "CTS",
    "CLS",
    "Assemblies",
    "Namespaces",
    "Dependency Injection",
    "Configuration",
    "Middleware",
    "Routing",
    "Controllers",
    "Minimal APIs",
    "Web APIs",
    "Model Binding",
    "Model Validation",
    "Entity Framework Core",
    "LINQ",
    "Authentication",
    "Authorization",
    "Exception Handling",
    "Logging",
    "Caching",
    "Async Programming",
    "Background Services",
    "Application Configuration",
  ],

  Go: [
    "Variables",
    "Data Types",
    "Constants",
    "Operators",
    "Type Conversion",
    "Conditional Statements",
    "Loops",
    "Functions",
    "Multiple Return Values",
    "Pointers",
    "Structs",
    "Methods",
    "Interfaces",
    "Embedding",
    "Packages",
    "Modules",
    "Error Handling",
    "Goroutines",
    "Channels",
    "Select Statement",
    "Concurrency",
    "Mutexes",
    "Context",
    "Generics",
    "Reflection",
  ],

  PHP: [
    "Variables",
    "Data Types",
    "Operators",
    "Type Conversion",
    "Conditional Statements",
    "Loops",
    "Functions",
    "Anonymous Functions",
    "Closures",
    "Scope",
    "Arrays",
    "Strings",
    "Classes and Objects",
    "Constructors",
    "Inheritance",
    "Interfaces",
    "Traits",
    "Namespaces",
    "Exception Handling",
    "Error Handling",
    "Sessions",
    "Cookies",
    "File Handling",
    "Database Connectivity",
    "Composer",
  ],

  Laravel: [
    "Application Structure",
    "Routing",
    "Controllers",
    "Middleware",
    "Requests",
    "Responses",
    "Blade Templates",
    "Blade Components",
    "Forms",
    "Validation",
    "Sessions",
    "Cookies",
    "Authentication",
    "Authorization",
    "Service Container",
    "Service Providers",
    "Facades",
    "Eloquent ORM",
    "Models",
    "Migrations",
    "Relationships",
    "Query Builder",
    "Queues",
    "Events and Listeners",
    "API Resources",
  ],

  Ruby: [
    "Variables",
    "Data Types",
    "Operators",
    "Type Conversion",
    "Conditional Statements",
    "Loops",
    "Methods",
    "Blocks",
    "Procs",
    "Lambdas",
    "Arrays",
    "Hashes",
    "Strings",
    "Symbols",
    "Classes and Objects",
    "Inheritance",
    "Modules",
    "Mixins",
    "Encapsulation",
    "Exception Handling",
    "Iterators",
    "Enumerables",
    "Gems",
    "Metaprogramming",
    "Garbage Collection",
  ],

  // =========================
  // DATABASE
  // =========================

  SQL: [
    "SELECT Queries",
    "WHERE Clause",
    "ORDER BY Clause",
    "GROUP BY Clause",
    "HAVING Clause",
    "Aggregate Functions",
    "String Functions",
    "Date Functions",
    "NULL Values",
    "DISTINCT",
    "LIMIT and OFFSET",
    "Joins",
    "INNER JOIN",
    "LEFT JOIN",
    "RIGHT JOIN",
    "FULL JOIN",
    "Subqueries",
    "Common Table Expressions",
    "Window Functions",
    "CASE Expressions",
    "Primary Keys",
    "Foreign Keys",
    "Constraints",
    "Indexes",
    "Transactions",
  ],

  PostgreSQL: [
    "Database and Schema",
    "Tables",
    "Data Types",
    "Constraints",
    "Primary Keys",
    "Foreign Keys",
    "Sequences",
    "Indexes",
    "Composite Indexes",
    "Partial Indexes",
    "Unique Indexes",
    "Views",
    "Materialized Views",
    "Functions",
    "Stored Procedures",
    "Triggers",
    "Transactions",
    "Isolation Levels",
    "Locks",
    "MVCC",
    "JSON and JSONB",
    "Array Data Types",
    "Common Table Expressions",
    "Window Functions",
    "Full-Text Search",
  ],

  MySQL: [
    "Database and Schema",
    "Tables",
    "Data Types",
    "Constraints",
    "Primary Keys",
    "Foreign Keys",
    "Unique Constraints",
    "Indexes",
    "Composite Indexes",
    "Views",
    "Stored Procedures",
    "Functions",
    "Triggers",
    "Transactions",
    "Isolation Levels",
    "Locks",
    "ACID Properties",
    "Joins",
    "Subqueries",
    "Common Table Expressions",
    "Window Functions",
    "JSON Data",
    "Normalization",
    "Query Optimization",
    "EXPLAIN",
  ],

  SQLite: [
    "Database Files",
    "Tables",
    "Data Types",
    "Constraints",
    "Primary Keys",
    "Foreign Keys",
    "Indexes",
    "Composite Indexes",
    "Unique Constraints",
    "Views",
    "Triggers",
    "Transactions",
    "ACID Properties",
    "Journaling",
    "WAL Mode",
    "Joins",
    "Subqueries",
    "Common Table Expressions",
    "Window Functions",
    "Aggregate Functions",
    "JSON Functions",
    "Full-Text Search",
    "Query Optimization",
    "SQLite Pragmas",
    "Concurrency",
  ],

  MongoDB: [
    "Databases",
    "Collections",
    "Documents",
    "BSON",
    "Data Types",
    "CRUD Operations",
    "Insert Operations",
    "Query Operations",
    "Update Operations",
    "Delete Operations",
    "Query Operators",
    "Array Operators",
    "Projection",
    "Sorting",
    "Pagination",
    "Indexes",
    "Compound Indexes",
    "Text Indexes",
    "Aggregation",
    "Aggregation Pipeline",
    "Aggregation Operators",
    "Lookup",
    "Schema Design",
    "Transactions",
    "Replication",
  ],

  Redis: [
    "Key-Value Data Model",
    "Strings",
    "Lists",
    "Sets",
    "Sorted Sets",
    "Hashes",
    "Streams",
    "Bitmaps",
    "HyperLogLog",
    "Geospatial Data",
    "TTL and Expiration",
    "Persistence",
    "RDB Snapshots",
    "AOF Persistence",
    "Eviction Policies",
    "Memory Management",
    "Transactions",
    "Pipelining",
    "Pub/Sub",
    "Lua Scripting",
    "Distributed Locks",
    "Caching",
    "Session Storage",
    "Rate Limiting",
    "Redis Cluster",
  ],

  // =========================
  // DEVOPS & CLOUD
  // =========================

  Git: [
    "Repositories",
    "Working Directory",
    "Staging Area",
    "Commits",
    "Branches",
    "Branch Merging",
    "Merge Conflicts",
    "Rebasing",
    "Remote Repositories",
    "Cloning",
    "Fetching",
    "Pulling",
    "Pushing",
    "Tags",
    "Gitignore",
    "Git Hooks",
    "Stashing",
    "Cherry-Picking",
    "Reverting",
    "Resetting",
    "Reflog",
    "Bisect",
    "Git Workflows",
    "Git Branching Strategies",
  ],

  GitHub: [
    "Repositories",
    "README Files",
    "Branches",
    "Commits",
    "Pull Requests",
    "Code Reviews",
    "Issues",
    "Discussions",
    "Forks",
    "Cloning",
    "GitHub Actions",
    "Workflows",
    "Secrets",
    "Environments",
    "GitHub Pages",
    "Releases",
    "Tags",
    "Packages",
    "Webhooks",
    "Deploy Keys",
    "SSH Keys",
    "Personal Access Tokens",
    "Branch Protection",
    "Collaborators",
    "Organizations",
  ],

  Linux: [
    "File System",
    "File Permissions",
    "Users and Groups",
    "Processes",
    "Signals",
    "Environment Variables",
    "Shell",
    "Bash",
    "Command Line",
    "File Operations",
    "Text Processing",
    "Pipes and Redirection",
    "Process Management",
    "Package Management",
    "System Services",
    "systemd",
    "Networking",
    "SSH",
    "Cron Jobs",
    "Logs",
    "Disk Management",
    "Memory Management",
    "CPU Management",
    "Shell Scripting",
    "Linux Security",
  ],

  Docker: [
    "Containers",
    "Images",
    "Dockerfile",
    "Docker Engine",
    "Docker CLI",
    "Docker Hub",
    "Container Lifecycle",
    "Container Networking",
    "Container Ports",
    "Container Volumes",
    "Bind Mounts",
    "Environment Variables",
    "Docker Compose",
    "Compose Services",
    "Compose Networks",
    "Compose Volumes",
    "Container Logs",
    "Container Resource Limits",
    "Container Health Checks",
    "Image Layers",
    "Image Tags",
    "Image Registry",
    "Multi-Stage Builds",
    "Container Security",
    "Docker Build Cache",
  ],

  Kubernetes: [
    "Cluster Architecture",
    "Nodes",
    "Pods",
    "Containers",
    "Deployments",
    "ReplicaSets",
    "Services",
    "Namespaces",
    "Labels and Selectors",
    "ConfigMaps",
    "Secrets",
    "Volumes",
    "Persistent Volumes",
    "Persistent Volume Claims",
    "Storage Classes",
    "Ingress",
    "Service Accounts",
    "RBAC",
    "Health Probes",
    "Resource Requests and Limits",
    "Horizontal Pod Autoscaling",
    "Rolling Updates",
    "Jobs and CronJobs",
    "DaemonSets",
    "StatefulSets",
  ],

  AWS: [
    "AWS Global Infrastructure",
    "AWS Regions",
    "Availability Zones",
    "AWS IAM",
    "IAM Users",
    "IAM Roles",
    "IAM Policies",
    "IAM Groups",
    "Amazon EC2",
    "EC2 Instance Types",
    "EC2 AMIs",
    "EC2 Security Groups",
    "EC2 Key Pairs",
    "EC2 Auto Scaling",
    "Elastic Load Balancing",
    "Amazon S3",
    "S3 Buckets",
    "S3 Storage Classes",
    "S3 Versioning",
    "S3 Lifecycle Policies",
    "Amazon VPC",
    "VPC Subnets",
    "Route Tables",
    "Internet Gateway",
    "NAT Gateway",
  ],

  "GitHub Actions": [
    "GitHub Actions",
    "Workflows",
    "Workflow Files",
    "Events",
    "Triggers",
    "Jobs",
    "Steps",
    "Actions",
    "Runners",
    "Hosted Runners",
    "Self-Hosted Runners",
    "Workflow Commands",
    "Environment Variables",
    "Secrets",
    "GitHub Variables",
    "Contexts",
    "Expressions",
    "Conditional Jobs",
    "Matrix Strategies",
    "Artifacts",
    "Caching",
    "Environments",
    "Deployment Protection",
    "Reusable Workflows",
    "CI/CD Pipelines",
  ],

  Terraform: [
    "Terraform",
    "Infrastructure as Code",
    "Terraform Architecture",
    "Terraform Workflow",
    "Terraform CLI",
    "Terraform Configuration",
    "Terraform Files",
    "Terraform Providers",
    "Provider Configuration",
    "Terraform Resources",
    "Resource Arguments",
    "Resource Attributes",
    "Data Sources",
    "Terraform Variables",
    "Input Variables",
    "Variable Types",
    "Variable Defaults",
    "Variable Validation",
    "Local Values",
    "Terraform Outputs",
    "Output Values",
    "Terraform Modules",
    "Module Sources",
    "Module Variables",
    "Terraform State",
  ],

  Nginx: [
    "Nginx Architecture",
    "Nginx Configuration",
    "nginx.conf",
    "Nginx Directives",
    "Nginx Contexts",
    "Server Blocks",
    "Location Blocks",
    "HTTP Request Processing",
    "Static File Serving",
    "Reverse Proxy",
    "Proxy Pass",
    "Proxy Headers",
    "Load Balancing",
    "Nginx Upstream",
    "Load Balancing Methods",
    "SSL/TLS Configuration",
    "HTTPS",
    "SSL Certificates",
    "HTTP/2",
    "HTTP/3",
    "Nginx Caching",
    "Gzip Compression",
    "Rate Limiting",
    "Access Control",
    "Nginx Logging",
  ],

  "Microsoft Azure": [
    "Azure Global Infrastructure",
    "Azure Regions",
    "Azure Availability Zones",
    "Azure Resource Groups",
    "Azure Subscriptions",
    "Azure Resource Manager",
    "Microsoft Entra ID",
    "Azure RBAC",
    "Azure Virtual Machines",
    "Azure VM Scale Sets",
    "Azure App Service",
    "Azure Functions",
    "Azure Container Instances",
    "Azure Kubernetes Service",
    "Azure Storage",
    "Azure Blob Storage",
    "Azure Files",
    "Azure Storage Tiers",
    "Azure Storage Replication",
    "Azure Virtual Network",
    "Azure Subnets",
    "Network Security Groups",
    "Azure Load Balancer",
    "Azure Application Gateway",
    "Azure Front Door",
  ],

  "Google Cloud": [
    "Google Cloud Platform",
    "Google Cloud Regions",
    "Google Cloud Zones",
    "Google Cloud Resource Hierarchy",
    "Google Cloud Projects",
    "Google Cloud Organization",
    "Google Cloud Folders",
    "Google Cloud IAM",
    "IAM Roles",
    "IAM Policies",
    "Service Accounts",
    "Compute Engine",
    "Compute Engine Machine Types",
    "Compute Engine Images",
    "Managed Instance Groups",
    "Cloud Load Balancing",
    "Cloud Storage",
    "Cloud Storage Buckets",
    "Cloud Storage Classes",
    "Cloud Storage Lifecycle Management",
    "Virtual Private Cloud",
    "VPC Networks",
    "VPC Subnets",
    "Cloud Firewall Rules",
    "Cloud DNS",
  ],

  GitLab: [
    "Repositories",
    "Projects",
    "Groups",
    "Branches",
    "Commits",
    "Merge Requests",
    "Code Reviews",
    "Issues",
    "Milestones",
    "Labels",
    "GitLab CI/CD",
    "Pipelines",
    "Jobs",
    "Runners",
    "Pipeline Variables",
    "CI/CD Variables",
    "Environments",
    "Deployments",
    "Artifacts",
    "Caching",
    "Container Registry",
    "Package Registry",
    "Webhooks",
    "Protected Branches",
    "Access Control",
  ],

  Jenkins: [
    "Jenkins Architecture",
    "Jenkins Installation",
    "Jenkins Configuration",
    "Jenkins Dashboard",
    "Jenkins Jobs",
    "Freestyle Projects",
    "Jenkins Pipelines",
    "Declarative Pipeline",
    "Scripted Pipeline",
    "Jenkinsfile",
    "Pipeline Stages",
    "Pipeline Steps",
    "Pipeline Syntax",
    "Jenkins Agents",
    "Jenkins Nodes",
    "Jenkins Executors",
    "Distributed Builds",
    "Build Triggers",
    "Webhook Triggers",
    "Scheduled Builds",
    "Parameterized Builds",
    "Build Parameters",
    "Build History",
    "Plugins",
    "Credentials",
  ],

  Ansible: [
    "Ansible",
    "Configuration Management",
    "Ansible Architecture",
    "Control Node",
    "Managed Nodes",
    "Inventory",
    "Static Inventory",
    "Dynamic Inventory",
    "Host Patterns",
    "Ad Hoc Commands",
    "Playbooks",
    "Playbook Structure",
    "Plays",
    "Tasks",
    "Modules",
    "Module Arguments",
    "Facts",
    "Gathering Facts",
    "Variables",
    "Variable Precedence",
    "Templates",
    "Jinja2",
    "Handlers",
    "Roles",
    "Role Directory Structure",
  ],

  // =========================
  // SYSTEM DESIGN
  // =========================

  "Distributed Systems": [
    "Distributed Systems Architecture",
    "Distributed Computing",
    "Distributed System Models",
    "Client-Server Architecture",
    "Peer-to-Peer Architecture",
    "Service-Oriented Architecture",
    "Microservices Architecture",
    "Scalability",
    "Horizontal Scaling",
    "Vertical Scaling",
    "Load Balancing",
    "Fault Tolerance",
    "High Availability",
    "Reliability",
    "Redundancy",
    "Replication",
    "Data Partitioning",
    "Sharding",
    "Consistency",
    "Strong Consistency",
    "Eventual Consistency",
    "CAP Theorem",
    "Consistency Models",
    "Distributed Transactions",
    "Distributed Consensus",
  ],

  Microservices: [
    "Microservices Architecture",
    "Microservice Design Principles",
    "Service Decomposition",
    "Bounded Contexts",
    "Service Independence",
    "Inter-Service Communication",
    "Synchronous Communication",
    "Asynchronous Communication",
    "REST APIs",
    "gRPC",
    "Message Brokers",
    "Event-Driven Architecture",
    "API Gateway",
    "Service Discovery",
    "Load Balancing",
    "Database per Service",
    "Distributed Transactions",
    "Saga Pattern",
    "CQRS",
    "Event Sourcing",
    "Circuit Breaker",
    "Retry Pattern",
    "Timeouts",
    "Distributed Tracing",
    "Observability",
  ],

  "REST API": [
    "REST Architecture",
    "REST Constraints",
    "RESTful Resources",
    "Resource Representation",
    "URI Design",
    "HTTP Methods",
    "GET Requests",
    "POST Requests",
    "PUT Requests",
    "PATCH Requests",
    "DELETE Requests",
    "HTTP Status Codes",
    "HTTP Headers",
    "Request Headers",
    "Response Headers",
    "Request Body",
    "Response Body",
    "Path Parameters",
    "Query Parameters",
    "Content Negotiation",
    "JSON",
    "Idempotency",
    "Statelessness",
    "REST API Versioning",
    "API Security",
  ],

  Caching: [
    "Caching",
    "Cache Architecture",
    "Cache-Aside",
    "Read-Through Cache",
    "Write-Through Cache",
    "Write-Behind Cache",
    "Write-Around Cache",
    "Cache Hit",
    "Cache Miss",
    "Cache Hit Ratio",
    "Cache Keys",
    "Cache Invalidation",
    "Cache Expiration",
    "TTL",
    "LRU",
    "LFU",
    "Distributed Caching",
    "Application Caching",
    "Database Caching",
    "HTTP Caching",
    "CDN Caching",
    "Redis Caching",
    "Cache Stampede",
    "Cache Penetration",
    "Cache Consistency",
  ],

  "Load Balancing": [
    "Load Balancing",
    "Load Balancer Architecture",
    "Client-Side Load Balancing",
    "Server-Side Load Balancing",
    "Layer 4 Load Balancing",
    "Layer 7 Load Balancing",
    "Reverse Proxy Load Balancing",
    "Round Robin",
    "Weighted Round Robin",
    "Least Connections",
    "IP Hash",
    "Consistent Hashing",
    "Health Checks",
    "Session Persistence",
    "Sticky Sessions",
    "Stateless Load Balancing",
    "Failover",
    "High Availability",
    "Horizontal Scaling",
    "Load Balancing in Distributed Systems",
  ],

  WebSockets: [
    "WebSocket Protocol",
    "WebSocket Architecture",
    "WebSocket Connection",
    "WebSocket Handshake",
    "HTTP Upgrade Request",
    "WebSocket Frames",
    "Text Frames",
    "Binary Frames",
    "Ping and Pong",
    "WebSocket Events",
    "WebSocket Client",
    "WebSocket Server",
    "Real-Time Communication",
    "Full-Duplex Communication",
    "Persistent Connections",
    "Connection Management",
    "Connection Lifecycle",
    "Reconnection",
    "Heartbeat",
    "Broadcasting",
    "Rooms and Channels",
    "Authentication",
    "Authorization",
    "WebSocket Security",
    "Scaling WebSockets",
  ],

  Kafka: [
    "Apache Kafka",
    "Kafka Architecture",
    "Kafka Brokers",
    "Kafka Clusters",
    "Kafka Topics",
    "Kafka Partitions",
    "Kafka Replication",
    "Kafka Producers",
    "Kafka Consumers",
    "Consumer Groups",
    "Consumer Offsets",
    "Kafka Messages",
    "Message Keys",
    "Kafka Records",
    "Producer Acknowledgments",
    "Delivery Semantics",
    "At-Most-Once Delivery",
    "At-Least-Once Delivery",
    "Exactly-Once Semantics",
    "Kafka Retention",
    "Log Compaction",
    "Consumer Rebalancing",
    "Leader Election",
    "Kafka Security",
    "Kafka Performance",
  ],

  GraphQL: [
    "GraphQL Architecture",
    "GraphQL Schema",
    "GraphQL Types",
    "Object Types",
    "Scalar Types",
    "Enum Types",
    "Input Object Types",
    "Interfaces",
    "Unions",
    "Fields",
    "Arguments",
    "Queries",
    "Mutations",
    "Subscriptions",
    "Resolvers",
    "Resolver Arguments",
    "Context",
    "Variables",
    "Fragments",
    "Aliases",
    "Directives",
    "Introspection",
    "Validation",
    "Error Handling",
    "GraphQL Security",
  ],

  RabbitMQ: [
    "RabbitMQ Architecture",
    "RabbitMQ Broker",
    "Exchanges",
    "Direct Exchange",
    "Fanout Exchange",
    "Topic Exchange",
    "Headers Exchange",
    "Queues",
    "Queue Bindings",
    "Routing Keys",
    "Producers",
    "Consumers",
    "AMQP",
    "Messages",
    "Acknowledgments",
    "Negative Acknowledgments",
    "Message Durability",
    "Persistent Messages",
    "Prefetch Count",
    "Dead Letter Exchanges",
    "Dead Letter Queues",
    "Message TTL",
    "Publisher Confirms",
    "Consumer Prefetch",
    "RabbitMQ Clustering",
  ],

  CDN: [
    "CDN Architecture",
    "CDN Edge Servers",
    "Points of Presence",
    "Origin Server",
    "Edge Computing",
    "Content Delivery",
    "Static Content Delivery",
    "Dynamic Content Delivery",
    "CDN Caching",
    "Cache-Control",
    "Cache Expiration",
    "Cache Invalidation",
    "Cache Purging",
    "Cache Hit",
    "Cache Miss",
    "Cache Key",
    "Origin Pull",
    "Origin Shield",
    "CDN Routing",
    "Geo-Based Routing",
    "Anycast Routing",
    "CDN Load Balancing",
    "CDN Security",
    "DDoS Protection",
    "Edge Functions",
  ],

  Elasticsearch: [
    "Elasticsearch Architecture",
    "Elasticsearch Cluster",
    "Elasticsearch Nodes",
    "Indices",
    "Documents",
    "Fields",
    "Document Mapping",
    "Dynamic Mapping",
    "Explicit Mapping",
    "Data Types",
    "Text Fields",
    "Keyword Fields",
    "Indexing",
    "Inverted Index",
    "Analyzers",
    "Tokenizers",
    "Token Filters",
    "Full-Text Search",
    "Term Queries",
    "Match Queries",
    "Boolean Queries",
    "Range Queries",
    "Query DSL",
    "Aggregations",
    "Shards and Replicas",
  ],

  Serverless: [
    "Serverless Architecture",
    "Serverless Computing",
    "Function as a Service",
    "Serverless Functions",
    "Function Invocation",
    "Event-Driven Architecture",
    "Event Sources",
    "Triggers",
    "Cold Starts",
    "Warm Starts",
    "Function Execution",
    "Stateless Functions",
    "Function Concurrency",
    "Function Timeouts",
    "Function Scaling",
    "Automatic Scaling",
    "Serverless APIs",
    "API Gateway",
    "Serverless Databases",
    "Serverless Storage",
    "Serverless Messaging",
    "Serverless Authentication",
    "Serverless Deployment",
    "Serverless Monitoring",
    "Serverless Security",
  ],

  // =========================
  // AI / ML
  // =========================

  "Machine Learning": [
    "Machine Learning",
    "Supervised Learning",
    "Unsupervised Learning",
    "Semi-Supervised Learning",
    "Reinforcement Learning",
    "Regression",
    "Classification",
    "Clustering",
    "Feature Engineering",
    "Feature Selection",
    "Data Preprocessing",
    "Training Data",
    "Validation Data",
    "Test Data",
    "Train-Test Split",
    "Cross-Validation",
    "Overfitting",
    "Underfitting",
    "Bias and Variance",
    "Regularization",
    "Linear Regression",
    "Logistic Regression",
    "Decision Trees",
    "Random Forest",
    "Support Vector Machines",
  ],

  "Deep Learning": [
    "Neural Networks",
    "Artificial Neurons",
    "Perceptrons",
    "Activation Functions",
    "Forward Propagation",
    "Backpropagation",
    "Loss Functions",
    "Gradient Descent",
    "Learning Rate",
    "Batch Training",
    "Epochs",
    "Weights and Biases",
    "Weight Initialization",
    "Regularization",
    "Dropout",
    "Batch Normalization",
    "Convolutional Neural Networks",
    "Convolution Layers",
    "Pooling Layers",
    "Recurrent Neural Networks",
    "Long Short-Term Memory",
    "Gated Recurrent Units",
    "Autoencoders",
    "Transfer Learning",
    "Model Evaluation",
  ],

  PyTorch: [
    "PyTorch Architecture",
    "Tensors",
    "Tensor Shapes",
    "Tensor Data Types",
    "Tensor Operations",
    "Tensor Indexing",
    "Tensor Reshaping",
    "Tensor Broadcasting",
    "CPU and GPU Tensors",
    "CUDA",
    "Autograd",
    "Automatic Differentiation",
    "Computational Graphs",
    "Neural Network Modules",
    "torch.nn",
    "Model Building",
    "Forward Pass",
    "Backpropagation",
    "Loss Functions",
    "Optimizers",
    "Learning Rate",
    "Training Loop",
    "Evaluation Mode",
    "DataLoader",
    "Dataset",
  ],

  TensorFlow: [
    "TensorFlow Architecture",
    "Tensors",
    "Tensor Shapes",
    "Tensor Data Types",
    "Tensor Operations",
    "Tensor Indexing",
    "Tensor Reshaping",
    "Tensor Broadcasting",
    "Variables",
    "Automatic Differentiation",
    "Gradient Computation",
    "Computational Graphs",
    "Eager Execution",
    "tf.data",
    "Data Pipelines",
    "TensorFlow Datasets",
    "Keras API",
    "Neural Network Layers",
    "Model Building",
    "Model Compilation",
    "Model Training",
    "Loss Functions",
    "Optimizers",
    "Model Evaluation",
    "Model Saving and Loading",
  ],

  Transformers: [
    "Transformer Architecture",
    "Encoder",
    "Decoder",
    "Encoder-Decoder Architecture",
    "Self-Attention",
    "Multi-Head Attention",
    "Query, Key, and Value",
    "Scaled Dot-Product Attention",
    "Positional Encoding",
    "Token Embeddings",
    "Feed-Forward Network",
    "Residual Connections",
    "Layer Normalization",
    "Attention Masking",
    "Causal Attention",
    "Cross-Attention",
    "Autoregressive Generation",
    "Transformer Training",
    "Pretraining",
    "Fine-Tuning",
    "Transfer Learning",
    "BERT",
    "GPT",
    "Vision Transformers",
    "Transformer Inference",
  ],

  LLMs: [
    "Large Language Models",
    "LLM Architecture",
    "Transformer Architecture",
    "Tokenization",
    "Tokens",
    "Token Embeddings",
    "Positional Embeddings",
    "Context Window",
    "Self-Attention",
    "Multi-Head Attention",
    "Causal Attention",
    "Feed-Forward Networks",
    "Layer Normalization",
    "Residual Connections",
    "Pretraining",
    "Next-Token Prediction",
    "Language Modeling",
    "Fine-Tuning",
    "Instruction Tuning",
    "Supervised Fine-Tuning",
    "RLHF",
    "Preference Optimization",
    "Prompt Engineering",
    "Inference",
    "LLM Evaluation",
  ],

  "Generative AI": [
    "Generative AI",
    "Generative Models",
    "Foundation Models",
    "Large Language Models",
    "Diffusion Models",
    "Generative Adversarial Networks",
    "Variational Autoencoders",
    "Transformer Models",
    "Text Generation",
    "Image Generation",
    "Audio Generation",
    "Video Generation",
    "Multimodal AI",
    "Prompt Engineering",
    "Few-Shot Prompting",
    "Zero-Shot Prompting",
    "Retrieval-Augmented Generation",
    "Fine-Tuning",
    "Parameter-Efficient Fine-Tuning",
    "Model Inference",
    "AI Agents",
    "AI Hallucinations",
    "Generative AI Evaluation",
    "Safety",
    "Guardrails",
  ],

  RAG: [
    "RAG Architecture",
    "Retrieval-Augmented Generation",
    "Document Ingestion",
    "Document Loading",
    "Document Parsing",
    "Text Chunking",
    "Chunk Size",
    "Chunk Overlap",
    "Embeddings",
    "Embedding Models",
    "Vector Databases",
    "Vector Indexing",
    "Similarity Search",
    "Cosine Similarity",
    "Semantic Search",
    "Keyword Search",
    "Hybrid Search",
    "Metadata Filtering",
    "Top-K Retrieval",
    "Retrieval Re-ranking",
    "Context Retrieval",
    "Context Window",
    "Prompt Construction",
    "Grounded Generation",
    "RAG Evaluation",
  ],

  "AI Agents": [
    "AI Agent Architecture",
    "Agentic AI",
    "Agents and Environments",
    "Agent Goals",
    "Agent Planning",
    "Agent Reasoning",
    "Agent Memory",
    "Short-Term Memory",
    "Long-Term Memory",
    "Tool Use",
    "Tool Calling",
    "Function Calling",
    "Agent Actions",
    "Agent Observation",
    "Agent State",
    "Agent Loops",
    "ReAct Pattern",
    "Task Decomposition",
    "Multi-Step Reasoning",
    "Workflow Agents",
    "Autonomous Agents",
    "Multi-Agent Systems",
    "Agent Orchestration",
    "Agent Communication",
    "Agent Evaluation",
  ],

  NLP: [
    "Natural Language Processing",
    "Text Preprocessing",
    "Tokenization",
    "Sentence Tokenization",
    "Word Tokenization",
    "Stop Words",
    "Stemming",
    "Lemmatization",
    "Part-of-Speech Tagging",
    "Named Entity Recognition",
    "Text Normalization",
    "Bag of Words",
    "TF-IDF",
    "N-Grams",
    "Word Embeddings",
    "Word2Vec",
    "GloVe",
    "Text Classification",
    "Sentiment Analysis",
    "Language Modeling",
    "Sequence-to-Sequence Models",
    "Attention Mechanism",
    "Transformer Architecture",
    "Text Summarization",
    "Question Answering",
  ],

  "Computer Vision": [
    "Image Representation",
    "Image Pixels",
    "Color Spaces",
    "Image Resizing",
    "Image Cropping",
    "Image Filtering",
    "Image Smoothing",
    "Edge Detection",
    "Thresholding",
    "Image Segmentation",
    "Feature Detection",
    "Feature Extraction",
    "Object Detection",
    "Object Recognition",
    "Image Classification",
    "Face Detection",
    "Face Recognition",
    "Optical Character Recognition",
    "Convolutional Neural Networks",
    "Image Augmentation",
    "Transfer Learning",
    "Semantic Segmentation",
    "Instance Segmentation",
    "Pose Estimation",
    "Optical Flow",
  ],

  HuggingFace: [
    "Hugging Face Hub",
    "Transformers",
    "Datasets",
    "Tokenizers",
    "Model Hub",
    "Dataset Hub",
    "Pretrained Models",
    "Model Configuration",
    "Auto Classes",
    "AutoTokenizer",
    "AutoModel",
    "Pipeline API",
    "Text Classification",
    "Text Generation",
    "Question Answering",
    "Named Entity Recognition",
    "Summarization",
    "Translation",
    "Embeddings",
    "Fine-Tuning",
    "Trainer API",
    "TrainingArguments",
    "Parameter-Efficient Fine-Tuning",
    "Quantization",
    "Inference",
  ],

  LangChain: [
    "LangChain Architecture",
    "LangChain Components",
    "Models",
    "Chat Models",
    "Prompt Templates",
    "Chat Prompt Templates",
    "Output Parsers",
    "Document Loaders",
    "Document Transformers",
    "Text Splitters",
    "Embeddings",
    "Vector Stores",
    "Retrievers",
    "Retrieval Chains",
    "RAG Chains",
    "Chains",
    "Runnable Interface",
    "LCEL",
    "LangChain Agents",
    "Tools",
    "Tool Calling",
    "Memory",
    "Message History",
    "Callbacks",
    "LangSmith",
  ],

  NumPy: [
    "NumPy Arrays",
    "Array Creation",
    "Array Dimensions",
    "Array Shape",
    "Array Size",
    "Array Data Types",
    "Array Indexing",
    "Array Slicing",
    "Boolean Indexing",
    "Fancy Indexing",
    "Array Reshaping",
    "Array Transpose",
    "Array Concatenation",
    "Array Splitting",
    "Array Stacking",
    "Broadcasting",
    "Vectorization",
    "Universal Functions",
    "Mathematical Operations",
    "Statistical Functions",
    "Aggregation Functions",
    "Random Number Generation",
    "Linear Algebra",
    "Memory Layout",
    "NumPy Performance",
  ],

  Pandas: [
    "Series",
    "DataFrame",
    "Index",
    "Creating DataFrames",
    "Reading Data",
    "Writing Data",
    "CSV Files",
    "Excel Files",
    "Data Selection",
    "Data Filtering",
    "Boolean Indexing",
    "DataFrame Indexing",
    "loc and iloc",
    "Adding and Removing Columns",
    "Sorting Data",
    "Handling Missing Data",
    "Data Cleaning",
    "Data Type Conversion",
    "Duplicate Data",
    "String Operations",
    "GroupBy",
    "Aggregation",
    "Merging and Joining",
    "Concatenation",
    "Pivot Tables",
  ],

  "Scikit-learn": [
    "Estimator API",
    "Training and Testing Data",
    "Train-Test Split",
    "Feature Scaling",
    "Standardization",
    "Normalization",
    "Feature Engineering",
    "Encoding Categorical Data",
    "Linear Regression",
    "Logistic Regression",
    "Decision Trees",
    "Random Forest",
    "Support Vector Machines",
    "K-Nearest Neighbors",
    "Naive Bayes",
    "Gradient Boosting",
    "K-Means Clustering",
    "Hierarchical Clustering",
    "Principal Component Analysis",
    "Dimensionality Reduction",
    "Model Evaluation",
    "Cross-Validation",
    "Hyperparameter Tuning",
    "Pipelines",
    "Model Persistence",
  ],

  Keras: [
    "Keras Architecture",
    "Keras Models",
    "Sequential API",
    "Functional API",
    "Model Subclassing",
    "Layers",
    "Dense Layers",
    "Convolutional Layers",
    "Pooling Layers",
    "Recurrent Layers",
    "Dropout",
    "Batch Normalization",
    "Activation Functions",
    "Input Layers",
    "Model Compilation",
    "Loss Functions",
    "Optimizers",
    "Metrics",
    "Model Training",
    "Training Callbacks",
    "Early Stopping",
    "Learning Rate Scheduling",
    "Model Evaluation",
    "Model Prediction",
    "Model Saving and Loading",
  ],

  LlamaIndex: [
    "LlamaIndex Architecture",
    "LlamaIndex Components",
    "Documents",
    "Nodes",
    "Document Parsing",
    "Document Ingestion",
    "Data Connectors",
    "Node Parsers",
    "Text Chunking",
    "Metadata",
    "Embeddings",
    "Embedding Models",
    "Vector Stores",
    "Vector Index",
    "Index Construction",
    "Query Engines",
    "Retrievers",
    "Retrieval Strategies",
    "Similarity Search",
    "Metadata Filtering",
    "Reranking",
    "Response Synthesis",
    "RAG Pipelines",
    "Agents",
    "Evaluation",
  ],

  // =========================
  // CS FUNDAMENTALS
  // =========================

  "Data Structures": [
    "Arrays",
    "Strings",
    "Linked Lists",
    "Singly Linked Lists",
    "Doubly Linked Lists",
    "Circular Linked Lists",
    "Stacks",
    "Queues",
    "Circular Queues",
    "Deques",
    "Hash Tables",
    "Hash Maps",
    "Hash Sets",
    "Trees",
    "Binary Trees",
    "Binary Search Trees",
    "AVL Trees",
    "Red-Black Trees",
    "Heaps",
    "Priority Queues",
    "Tries",
    "Graphs",
    "Directed Graphs",
    "Undirected Graphs",
    "Disjoint Set Union",
  ],

  Algorithms: [
    "Algorithm Complexity",
    "Big O Notation",
    "Time Complexity",
    "Space Complexity",
    "Recursion",
    "Backtracking",
    "Brute Force",
    "Divide and Conquer",
    "Greedy Algorithms",
    "Dynamic Programming",
    "Two Pointers",
    "Sliding Window",
    "Binary Search",
    "Sorting Algorithms",
    "Bubble Sort",
    "Selection Sort",
    "Insertion Sort",
    "Merge Sort",
    "Quick Sort",
    "Heap Sort",
    "Counting Sort",
    "Graph Traversal",
    "Breadth-First Search",
    "Depth-First Search",
    "Shortest Path Algorithms",
  ],

  OOP: [
    "Classes",
    "Objects",
    "Constructors",
    "Methods",
    "Properties",
    "Encapsulation",
    "Abstraction",
    "Inheritance",
    "Polymorphism",
    "Method Overloading",
    "Method Overriding",
    "Access Modifiers",
    "Public Members",
    "Private Members",
    "Protected Members",
    "Static Members",
    "Instance Members",
    "Abstract Classes",
    "Interfaces",
    "Composition",
    "Aggregation",
    "Association",
    "Dependency",
    "Object Relationships",
    "SOLID Principles",
  ],

  "Operating Systems": [
    "Operating System Architecture",
    "Kernel",
    "System Calls",
    "Processes",
    "Process States",
    "Process Scheduling",
    "Threads",
    "Multithreading",
    "Context Switching",
    "CPU Scheduling",
    "Scheduling Algorithms",
    "Inter-Process Communication",
    "Synchronization",
    "Race Conditions",
    "Deadlocks",
    "Deadlock Prevention",
    "Deadlock Avoidance",
    "Memory Management",
    "Virtual Memory",
    "Paging",
    "Segmentation",
    "Page Replacement",
    "File Systems",
    "I/O Management",
    "System Security",
  ],

  "Computer Networks": [
    "Network Architecture",
    "OSI Model",
    "TCP/IP Model",
    "Network Topologies",
    "Network Devices",
    "IP Addressing",
    "IPv4",
    "IPv6",
    "Subnetting",
    "MAC Addresses",
    "ARP",
    "DNS",
    "DHCP",
    "TCP",
    "UDP",
    "TCP Handshake",
    "HTTP",
    "HTTPS",
    "HTTP/2",
    "HTTP/3",
    "FTP",
    "SMTP",
    "Firewalls",
    "NAT",
    "Routing",
  ],

  DBMS: [
    "DBMS Architecture",
    "Database Models",
    "Relational Model",
    "Keys",
    "Primary Key",
    "Foreign Key",
    "Candidate Key",
    "Constraints",
    "Normalization",
    "First Normal Form",
    "Second Normal Form",
    "Third Normal Form",
    "BCNF",
    "Denormalization",
    "Transactions",
    "ACID Properties",
    "Concurrency Control",
    "Locking",
    "Deadlocks",
    "Isolation Levels",
    "Indexes",
    "Views",
    "Stored Procedures",
    "Triggers",
    "Database Backup and Recovery",
  ],

  Concurrency: [
    "Concurrency",
    "Parallelism",
    "Processes",
    "Threads",
    "Multithreading",
    "Asynchronous Programming",
    "Synchronous vs Asynchronous Execution",
    "Shared Memory",
    "Thread Safety",
    "Race Conditions",
    "Critical Sections",
    "Mutual Exclusion",
    "Locks",
    "Mutexes",
    "Semaphores",
    "Monitors",
    "Atomic Operations",
    "Compare-and-Swap",
    "Deadlocks",
    "Deadlock Prevention",
    "Deadlock Avoidance",
    "Starvation",
    "Livelock",
    "Thread Pools",
    "Concurrent Data Structures",
  ],

  "Software Engineering": [
    "Software Development Life Cycle",
    "Software Requirements",
    "Functional Requirements",
    "Non-Functional Requirements",
    "Software Design",
    "Software Architecture",
    "System Design",
    "Modular Design",
    "Separation of Concerns",
    "Coupling",
    "Cohesion",
    "Design Patterns",
    "Version Control",
    "Git Workflow",
    "Code Review",
    "Coding Standards",
    "Clean Code",
    "Refactoring",
    "Testing",
    "Unit Testing",
    "Integration Testing",
    "System Testing",
    "Test-Driven Development",
    "Continuous Integration",
    "Continuous Delivery",
  ],

  "Compiler Design": [
    "Compiler Architecture",
    "Compiler Phases",
    "Lexical Analysis",
    "Lexical Analyzer",
    "Tokens",
    "Regular Expressions",
    "Finite Automata",
    "Syntax Analysis",
    "Parser",
    "Context-Free Grammar",
    "Parse Trees",
    "Abstract Syntax Trees",
    "Top-Down Parsing",
    "Bottom-Up Parsing",
    "Semantic Analysis",
    "Symbol Table",
    "Type Checking",
    "Intermediate Code Generation",
    "Three-Address Code",
    "Code Optimization",
    "Control Flow Graph",
    "Data Flow Analysis",
    "Code Generation",
    "Register Allocation",
    "Error Handling",
  ],

  "Computer Architecture": [
    "CPU Architecture",
    "Instruction Set Architecture",
    "Von Neumann Architecture",
    "Harvard Architecture",
    "CPU Components",
    "Control Unit",
    "Arithmetic Logic Unit",
    "Registers",
    "Program Counter",
    "Instruction Register",
    "Instruction Cycle",
    "Fetch Decode Execute Cycle",
    "Machine Instructions",
    "Instruction Formats",
    "Addressing Modes",
    "RISC",
    "CISC",
    "Pipelining",
    "Pipeline Hazards",
    "Cache Memory",
    "Cache Mapping",
    "Virtual Memory",
    "Memory Hierarchy",
    "Input Output Architecture",
    "CPU Performance",
  ],

  "React Native": [
  "React Native Architecture",
  "Components",
  "JSX",
  "Props",
  "State",
  "Hooks",
  "Styling",
  "Flexbox",
  "Platform APIs",
  "Platform-Specific Code",
  "Navigation",
  "Deep Linking",
  "Gestures",
  "Animations",
  "FlatList",
  "SectionList",
  "VirtualizedList",
  "Keyboard Handling",
  "Permissions",
  "Native Modules",
  "Native Components",
  "Async Storage",
  "Push Notifications",
  "Performance Optimization",
  "React Native Debugging",
],

"Flutter": [
  "Flutter Architecture",
  "Dart",
  "Widgets",
  "StatelessWidget",
  "StatefulWidget",
  "Widget Tree",
  "Build Method",
  "State Management",
  "InheritedWidget",
  "Provider",
  "Riverpod",
  "Navigation",
  "Routes",
  "Layouts",
  "Flexbox-Like Layouts",
  "Themes",
  "Animations",
  "Gestures",
  "Forms",
  "ListView",
  "GridView",
  "Async Programming",
  "Platform Channels",
  "Flutter Performance",
  "Flutter Debugging",
],

"Android": [
  "Android Architecture",
  "Android SDK",
  "Activities",
  "Fragments",
  "Intents",
  "Services",
  "Broadcast Receivers",
  "Content Providers",
  "Android Lifecycle",
  "ViewModel",
  "LiveData",
  "StateFlow",
  "RecyclerView",
  "Layouts",
  "Resources",
  "Permissions",
  "Notifications",
  "Storage",
  "Room Database",
  "Networking",
  "Background Work",
  "WorkManager",
  "Navigation",
  "Dependency Injection",
  "Android Performance",
],

"Kotlin": [
  "Kotlin Syntax",
  "Variables",
  "Data Types",
  "Null Safety",
  "Nullable Types",
  "Functions",
  "Lambda Expressions",
  "Higher-Order Functions",
  "Collections",
  "Lists",
  "Sets",
  "Maps",
  "Extension Functions",
  "Data Classes",
  "Sealed Classes",
  "Object Declarations",
  "Companion Objects",
  "Classes",
  "Interfaces",
  "Inheritance",
  "Coroutines",
  "Suspending Functions",
  "Flow",
  "Generics",
  "Kotlin DSL",
],

"Java": [
  "Java Syntax",
  "Variables",
  "Data Types",
  "Operators",
  "Control Flow",
  "Methods",
  "Arrays",
  "Strings",
  "Classes",
  "Objects",
  "Constructors",
  "Inheritance",
  "Polymorphism",
  "Encapsulation",
  "Abstraction",
  "Interfaces",
  "Exception Handling",
  "Collections Framework",
  "Generics",
  "Streams",
  "Lambda Expressions",
  "Multithreading",
  "Concurrency",
  "JVM",
  "Garbage Collection",
],

"iOS": [
  "iOS Architecture",
  "iOS SDK",
  "UIKit",
  "View Controllers",
  "View Lifecycle",
  "Navigation Controllers",
  "Tab Bar Controllers",
  "Auto Layout",
  "Storyboards",
  "Programmatic UI",
  "Table Views",
  "Collection Views",
  "UserDefaults",
  "Core Data",
  "Networking",
  "URLSession",
  "JSON Handling",
  "Push Notifications",
  "App Permissions",
  "Background Tasks",
  "App Lifecycle",
  "Deep Linking",
  "Accessibility",
  "App Security",
  "iOS Performance",
],

"Swift": [
  "Swift Syntax",
  "Variables",
  "Constants",
  "Data Types",
  "Optionals",
  "Optional Binding",
  "Functions",
  "Closures",
  "Collections",
  "Arrays",
  "Sets",
  "Dictionaries",
  "Structs",
  "Classes",
  "Enums",
  "Protocols",
  "Extensions",
  "Generics",
  "Error Handling",
  "Property Wrappers",
  "Memory Management",
  "ARC",
  "Concurrency",
  "Async Await",
  "Swift Actors",
],

"SwiftUI": [
  "SwiftUI Architecture",
  "Views",
  "View Composition",
  "State",
  "Binding",
  "Observable Objects",
  "Environment",
  "State Management",
  "Stacks",
  "Lists",
  "Grids",
  "Forms",
  "Navigation",
  "NavigationStack",
  "Sheets",
  "Alerts",
  "Animations",
  "Gestures",
  "Custom Views",
  "Modifiers",
  "Property Wrappers",
  "Async Data",
  "Accessibility",
  "Performance",
  "SwiftUI Lifecycle",
],

"Expo": [
  "Expo Architecture",
  "Expo CLI",
  "Expo SDK",
  "Expo Router",
  "File-Based Routing",
  "Expo Go",
  "Development Builds",
  "EAS Build",
  "EAS Submit",
  "EAS Update",
  "App Configuration",
  "Environment Variables",
  "Expo Modules",
  "Expo Camera",
  "Expo Location",
  "Expo Notifications",
  "Expo SecureStore",
  "Expo FileSystem",
  "Expo Image",
  "Expo AV",
  "Permissions",
  "Deep Linking",
  "Push Notifications",
  "Over-the-Air Updates",
  "Expo Performance",
],

"Jetpack Compose": [
  "Jetpack Compose Architecture",
  "Composable Functions",
  "Composition",
  "Recomposition",
  "State",
  "remember",
  "rememberSaveable",
  "State Hoisting",
  "MutableState",
  "Side Effects",
  "LaunchedEffect",
  "DisposableEffect",
  "Layouts",
  "Row",
  "Column",
  "Box",
  "LazyColumn",
  "LazyRow",
  "Modifiers",
  "Material Design",
  "Navigation",
  "Theming",
  "Animations",
  "Accessibility",
  "Compose Performance",
],

Jest: [
  "Jest Architecture",
  "Test Suites",
  "Test Cases",
  "Matchers",
  "Expect Assertions",
  "Setup and Teardown",
  "beforeEach and afterEach",
  "beforeAll and afterAll",
  "Mock Functions",
  "Mock Modules",
  "Mock Implementations",
  "Spies",
  "Timers",
  "Fake Timers",
  "Async Testing",
  "Promises",
  "Async Await",
  "Snapshot Testing",
  "Parameterized Tests",
  "Test Coverage",
  "Code Coverage Reports",
  "Jest Configuration",
  "Jest CLI",
  "Module Isolation",
  "Testing Best Practices",
],

Vitest: [
  "Vitest Architecture",
  "Test Suites",
  "Test Cases",
  "Matchers",
  "Expect Assertions",
  "Setup Files",
  "Test Hooks",
  "Mock Functions",
  "Module Mocking",
  "Spies",
  "Fake Timers",
  "Async Testing",
  "Promises",
  "Async Await",
  "Snapshot Testing",
  "Parameterized Tests",
  "Test Coverage",
  "Coverage Reports",
  "Vitest Configuration",
  "Vitest CLI",
  "Environment Configuration",
  "Browser Mode",
  "Test Isolation",
  "Watch Mode",
  "Vitest Best Practices",
],

Playwright: [
  "Playwright Architecture",
  "Browser Automation",
  "Browser Contexts",
  "Pages",
  "Locators",
  "CSS Selectors",
  "Text Selectors",
  "Role Selectors",
  "Element Actions",
  "Assertions",
  "Auto-Waiting",
  "Navigation",
  "Page Events",
  "Fixtures",
  "Test Hooks",
  "Authentication Testing",
  "API Testing",
  "Network Interception",
  "Request Mocking",
  "Screenshots",
  "Video Recording",
  "Trace Viewer",
  "Parallel Testing",
  "Cross-Browser Testing",
  "Playwright Best Practices",
],

Cypress: [
  "Cypress Architecture",
  "Test Runner",
  "Test Suites",
  "Test Cases",
  "Commands",
  "Assertions",
  "Selectors",
  "Element Queries",
  "Element Actions",
  "Automatic Waiting",
  "Fixtures",
  "Custom Commands",
  "Hooks",
  "Aliases",
  "Stubs",
  "Spies",
  "Clocks",
  "Network Interception",
  "Request Mocking",
  "API Testing",
  "Screenshots",
  "Videos",
  "Component Testing",
  "End-to-End Testing",
  "Cypress Best Practices",
],

Selenium: [
  "Selenium Architecture",
  "WebDriver",
  "WebDriver Commands",
  "Browser Drivers",
  "Locators",
  "ID Locator",
  "CSS Selectors",
  "XPath",
  "Element Interaction",
  "Explicit Waits",
  "Implicit Waits",
  "Fluent Waits",
  "Page Object Model",
  "Page Factory",
  "Test Fixtures",
  "Browser Windows",
  "IFrames",
  "Alerts",
  "Cookies",
  "Screenshots",
  "JavaScript Execution",
  "Selenium Grid",
  "Parallel Testing",
  "Cross-Browser Testing",
  "Selenium Best Practices",
],

"React Testing Library": [
  "React Testing Library Architecture",
  "Rendering Components",
  "Queries",
  "getBy Queries",
  "queryBy Queries",
  "findBy Queries",
  "Role Queries",
  "Text Queries",
  "Label Queries",
  "Placeholder Queries",
  "User Events",
  "userEvent",
  "Assertions",
  "Testing Forms",
  "Testing User Interactions",
  "Testing Async Components",
  "waitFor",
  "Mocking APIs",
  "Testing Context",
  "Testing Hooks",
  "Testing Custom Hooks",
  "Component Integration Testing",
  "Accessibility Testing",
  "Jest DOM",
  "Testing Best Practices",
],

PyTest: [
  "PyTest Architecture",
  "Test Functions",
  "Test Classes",
  "Assertions",
  "Fixtures",
  "Fixture Scope",
  "Fixture Dependencies",
  "Parameterized Tests",
  "Test Markers",
  "Skipping Tests",
  "Expected Failures",
  "Setup and Teardown",
  "conftest.py",
  "Mocking",
  "Monkeypatch",
  "Async Testing",
  "Exception Testing",
  "Temporary Files",
  "Test Discovery",
  "Test Configuration",
  "PyTest CLI",
  "Plugins",
  "Code Coverage",
  "Parallel Testing",
  "PyTest Best Practices",
],

JUnit: [
  "JUnit Architecture",
  "Test Classes",
  "Test Methods",
  "Assertions",
  "JUnit Lifecycle",
  "BeforeEach",
  "AfterEach",
  "BeforeAll",
  "AfterAll",
  "Parameterized Tests",
  "Test Fixtures",
  "Exception Testing",
  "Timeout Testing",
  "Nested Tests",
  "Repeated Tests",
  "Test Suites",
  "Assumptions",
  "Mocking with JUnit",
  "Integration Testing",
  "Test Discovery",
  "JUnit Configuration",
  "JUnit Platform",
  "JUnit Jupiter",
  "Code Coverage",
  "JUnit Best Practices",
],

Postman: [
  "Postman Architecture",
  "Collections",
  "Requests",
  "HTTP Methods",
  "Request Headers",
  "Request Body",
  "Query Parameters",
  "Path Parameters",
  "Authentication",
  "Bearer Tokens",
  "Environment Variables",
  "Collection Variables",
  "Pre-request Scripts",
  "Test Scripts",
  "Assertions",
  "Response Validation",
  "Request Chaining",
  "Mock Servers",
  "API Documentation",
  "Collection Runner",
  "Data-Driven Testing",
  "Postman CLI",
  "Newman",
  "API Monitoring",
  "Postman Best Practices",
],

Supertest: [
  "Supertest Architecture",
  "HTTP API Testing",
  "Express API Testing",
  "Request Methods",
  "Request Headers",
  "Request Body",
  "Query Parameters",
  "Path Parameters",
  "Response Status Codes",
  "Response Headers",
  "Response Body",
  "JSON Assertions",
  "Authentication Testing",
  "Cookie Testing",
  "Session Testing",
  "Async API Testing",
  "Error Response Testing",
  "Middleware Testing",
  "Route Testing",
  "Database Integration Testing",
  "Test Server Setup",
  "Jest Integration",
  "Vitest Integration",
  "API Test Isolation",
  "Supertest Best Practices",
],

"Unit Testing": [
  "Unit Testing Fundamentals",
  "Test Cases",
  "Test Suites",
  "Test Fixtures",
  "Assertions",
  "Test Isolation",
  "Test Independence",
  "Test Doubles",
  "Mocks",
  "Stubs",
  "Spies",
  "Fakes",
  "Dependency Injection",
  "Mocking Dependencies",
  "Boundary Testing",
  "Edge Case Testing",
  "Error Testing",
  "Exception Testing",
  "Parameterized Testing",
  "Test Coverage",
  "Code Coverage",
  "Test Maintainability",
  "Test Naming",
  "Fast Tests",
  "Unit Testing Best Practices",
],

"Integration Testing": [
  "Integration Testing Fundamentals",
  "Component Integration",
  "Module Integration",
  "Service Integration",
  "API Integration Testing",
  "Database Integration Testing",
  "Third-Party Integration Testing",
  "Integration Test Environment",
  "Test Fixtures",
  "Test Data Management",
  "Test Isolation",
  "Mocking External Services",
  "Test Containers",
  "Transaction Testing",
  "Authentication Integration",
  "Authorization Integration",
  "Error Handling",
  "Failure Scenarios",
  "Contract Testing",
  "Integration Test Automation",
  "Parallel Integration Tests",
  "Integration Test Coverage",
  "Test Environment Management",
  "Integration Test Debugging",
  "Integration Testing Best Practices",
],

"End-to-End Testing": [
  "End-to-End Testing Fundamentals",
  "User Flows",
  "Test Scenarios",
  "Browser Automation",
  "Page Objects",
  "Locators",
  "User Interactions",
  "Assertions",
  "Navigation Testing",
  "Form Testing",
  "Authentication Flows",
  "Authorization Flows",
  "API Integration",
  "Database Verification",
  "Test Data Management",
  "Fixtures",
  "Test Environment",
  "Cross-Browser Testing",
  "Responsive Testing",
  "Visual Testing",
  "Screenshot Testing",
  "Parallel Execution",
  "Flaky Test Management",
  "CI/CD Integration",
  "E2E Testing Best Practices",
],

"Load Testing": [
  "Load Testing Fundamentals",
  "Performance Testing",
  "Load Profiles",
  "Virtual Users",
  "Concurrent Users",
  "Requests Per Second",
  "Throughput",
  "Response Time",
  "Latency",
  "Percentile Latency",
  "Ramp-Up",
  "Ramp-Down",
  "Steady-State Load",
  "Stress Testing",
  "Spike Testing",
  "Endurance Testing",
  "Scalability Testing",
  "Capacity Testing",
  "Performance Bottlenecks",
  "Database Load Testing",
  "API Load Testing",
  "Distributed Load Testing",
  "Performance Monitoring",
  "Load Test Reporting",
  "Load Testing Best Practices",
],

"Web Security": [
  "Security Principles",
  "Threat Modeling",
  "Attack Surface",
  "Security Vulnerabilities",
  "Secure Coding",
  "Input Validation",
  "Output Encoding",
  "Session Security",
  "Cookie Security",
  "Browser Security",
  "Content Security Policy",
  "Security Headers",
  "Same-Origin Policy",
  "Web Application Firewall",
  "Rate Limiting",
  "Brute Force Protection",
  "Security Logging",
  "Security Monitoring",
  "Secrets Management",
  "Dependency Security",
  "Supply Chain Security",
  "Data Protection",
  "Secure API Design",
  "Security Testing",
  "Incident Response",
],

"OWASP": [
  "OWASP Top 10",
  "Broken Access Control",
  "Cryptographic Failures",
  "Injection",
  "Insecure Design",
  "Security Misconfiguration",
  "Vulnerable Components",
  "Authentication Failures",
  "Software Integrity Failures",
  "Logging and Monitoring Failures",
  "Server-Side Request Forgery",
  "OWASP ASVS",
  "OWASP API Security Top 10",
  "OWASP SAMM",
  "OWASP ZAP",
  "Threat Modeling",
  "Secure Development Lifecycle",
  "Security Testing",
  "Input Validation",
  "Output Encoding",
  "Access Control Testing",
  "Dependency Scanning",
  "Security Misconfiguration Testing",
  "Vulnerability Management",
  "Security Risk Assessment",
],

"Authentication": [
  "Authentication Fundamentals",
  "Identity Verification",
  "Credentials",
  "Password Authentication",
  "Password Hashing",
  "Password Salting",
  "Password Policies",
  "Multi-Factor Authentication",
  "Two-Factor Authentication",
  "Biometric Authentication",
  "Session-Based Authentication",
  "Token-Based Authentication",
  "Single Sign-On",
  "Identity Providers",
  "Account Lockout",
  "Brute Force Protection",
  "Credential Stuffing",
  "Password Reset",
  "Email Verification",
  "Session Management",
  "Authentication Cookies",
  "Authentication Tokens",
  "Authentication Flows",
  "Adaptive Authentication",
  "Authentication Security",
],

"Authorization": [
  "Authorization Fundamentals",
  "Access Control",
  "Role-Based Access Control",
  "Attribute-Based Access Control",
  "Permission Models",
  "User Roles",
  "Permissions",
  "Access Control Lists",
  "Resource-Based Authorization",
  "Policy-Based Authorization",
  "Least Privilege",
  "Privilege Escalation",
  "Horizontal Privilege Escalation",
  "Vertical Privilege Escalation",
  "Object-Level Authorization",
  "Function-Level Authorization",
  "Route Protection",
  "API Authorization",
  "Authorization Middleware",
  "Access Control Testing",
  "Multi-Tenant Authorization",
  "Delegated Authorization",
  "Authorization Policies",
  "Deny by Default",
  "Broken Access Control",
],

"OAuth": [
  "OAuth Fundamentals",
  "OAuth 2.0",
  "OAuth Roles",
  "Resource Owner",
  "Client",
  "Authorization Server",
  "Resource Server",
  "Authorization Code Flow",
  "PKCE",
  "Client Credentials Flow",
  "Refresh Tokens",
  "Access Tokens",
  "Scopes",
  "Redirect URIs",
  "State Parameter",
  "Nonce",
  "OAuth Consent",
  "Token Introspection",
  "Token Revocation",
  "Public Clients",
  "Confidential Clients",
  "OAuth Security",
  "OpenID Connect",
  "OAuth 2.1",
  "OAuth Threats",
],

"JWT": [
  "JWT Fundamentals",
  "JWT Structure",
  "JWT Header",
  "JWT Payload",
  "JWT Signature",
  "JWT Claims",
  "Registered Claims",
  "Custom Claims",
  "JWT Encoding",
  "JWT Signing",
  "Symmetric Signing",
  "Asymmetric Signing",
  "HMAC",
  "RSA",
  "ECDSA",
  "Access Tokens",
  "Refresh Tokens",
  "Token Expiration",
  "Token Validation",
  "Token Revocation",
  "JWT Storage",
  "JWT Security",
  "JWT Authentication",
  "JWT Authorization",
  "JWT Best Practices",
],

"HTTPS": [
  "HTTPS Fundamentals",
  "HTTP vs HTTPS",
  "HTTPS Architecture",
  "TLS Certificates",
  "Certificate Authorities",
  "Digital Certificates",
  "Certificate Validation",
  "Public Key Infrastructure",
  "TLS Handshake",
  "Encryption in Transit",
  "Server Authentication",
  "Perfect Forward Secrecy",
  "HTTP Strict Transport Security",
  "HSTS",
  "Mixed Content",
  "Secure Cookies",
  "TLS Versions",
  "HTTPS Redirects",
  "Certificate Expiration",
  "Certificate Pinning",
  "HTTPS for APIs",
  "HTTPS Performance",
  "HTTPS Security",
  "Man-in-the-Middle Protection",
  "HTTPS Best Practices",
],

"TLS": [
  "TLS Fundamentals",
  "TLS Architecture",
  "TLS Handshake",
  "TLS 1.2",
  "TLS 1.3",
  "ClientHello",
  "ServerHello",
  "Certificate Exchange",
  "Certificate Authorities",
  "Digital Certificates",
  "Public Key Cryptography",
  "Symmetric Encryption",
  "Key Exchange",
  "Diffie-Hellman",
  "Elliptic Curve Cryptography",
  "Cipher Suites",
  "Perfect Forward Secrecy",
  "Session Keys",
  "TLS Authentication",
  "TLS Record Protocol",
  "TLS Security",
  "Certificate Validation",
  "TLS Configuration",
  "TLS Vulnerabilities",
  "TLS Best Practices",
],

"CORS": [
  "CORS Fundamentals",
  "Same-Origin Policy",
  "Cross-Origin Requests",
  "CORS Headers",
  "Origin Header",
  "Access-Control-Allow-Origin",
  "Access-Control-Allow-Methods",
  "Access-Control-Allow-Headers",
  "Access-Control-Allow-Credentials",
  "Access-Control-Expose-Headers",
  "Access-Control-Max-Age",
  "Preflight Requests",
  "OPTIONS Requests",
  "Simple Requests",
  "Non-Simple Requests",
  "CORS Credentials",
  "CORS and Cookies",
  "CORS and Authentication",
  "CORS for APIs",
  "CORS Configuration",
  "CORS Middleware",
  "CORS Errors",
  "CORS Security",
  "CORS Misconfiguration",
  "CORS Best Practices",
],

"CSRF": [
  "CSRF Fundamentals",
  "CSRF Attacks",
  "Cross-Site Request Forgery",
  "Same-Origin Policy",
  "SameSite Cookies",
  "CSRF Tokens",
  "Synchronizer Token Pattern",
  "Double Submit Cookie",
  "Origin Header Validation",
  "Referer Header Validation",
  "CSRF Protection Middleware",
  "CSRF and Sessions",
  "CSRF and Authentication",
  "CSRF and Cookies",
  "CSRF in APIs",
  "CSRF in SPAs",
  "CSRF in Forms",
  "GET Request Safety",
  "POST Request Protection",
  "State-Changing Requests",
  "CSRF Token Rotation",
  "CSRF Token Validation",
  "CSRF Testing",
  "CSRF Bypass Risks",
  "CSRF Best Practices",
],

"XSS": [
  "XSS Fundamentals",
  "Reflected XSS",
  "Stored XSS",
  "DOM-Based XSS",
  "XSS Payloads",
  "Script Injection",
  "HTML Injection",
  "JavaScript Injection",
  "Input Sanitization",
  "Output Encoding",
  "HTML Encoding",
  "JavaScript Encoding",
  "URL Encoding",
  "Content Security Policy",
  "CSP Nonce",
  "CSP Hashes",
  "Trusted Types",
  "Safe DOM APIs",
  "innerHTML Security",
  "XSS in React",
  "XSS in APIs",
  "Cookie Theft Risks",
  "XSS Prevention",
  "XSS Testing",
  "XSS Best Practices",
],

"SQL Injection": [
  "SQL Injection Fundamentals",
  "SQL Injection Attacks",
  "Classic SQL Injection",
  "Union-Based SQL Injection",
  "Boolean-Based SQL Injection",
  "Time-Based SQL Injection",
  "Error-Based SQL Injection",
  "Blind SQL Injection",
  "Authentication Bypass",
  "Input Validation",
  "Parameterized Queries",
  "Prepared Statements",
  "Stored Procedures",
  "ORM Security",
  "Query Parameterization",
  "Dynamic SQL Security",
  "Database Permissions",
  "Least Privilege",
  "SQL Injection Prevention",
  "SQL Injection Testing",
  "SQL Injection Detection",
  "WAF Protection",
  "Database Security",
  "Secure Query Design",
  "SQL Injection Best Practices",
],

"Encryption": [
  "Encryption Fundamentals",
  "Symmetric Encryption",
  "Asymmetric Encryption",
  "Block Ciphers",
  "Stream Ciphers",
  "AES",
  "ChaCha20",
  "RSA",
  "Elliptic Curve Cryptography",
  "Public Key Cryptography",
  "Private Keys",
  "Public Keys",
  "Key Generation",
  "Key Exchange",
  "Key Management",
  "Key Rotation",
  "Initialization Vectors",
  "Nonces",
  "Encryption at Rest",
  "Encryption in Transit",
  "End-to-End Encryption",
  "Authenticated Encryption",
  "Cryptographic Hashing",
  "Digital Signatures",
  "Encryption Best Practices",
],

"Network Security": [
  "Network Security Fundamentals",
  "Network Threats",
  "Network Attacks",
  "Firewalls",
  "Web Application Firewalls",
  "Intrusion Detection Systems",
  "Intrusion Prevention Systems",
  "Network Segmentation",
  "Virtual Private Networks",
  "IPsec",
  "TLS",
  "Secure Network Protocols",
  "Network Authentication",
  "Network Access Control",
  "Zero Trust Security",
  "DDoS Protection",
  "Packet Filtering",
  "Port Security",
  "Network Monitoring",
  "Security Information and Event Management",
  "DNS Security",
  "Email Security",
  "Wireless Network Security",
  "Network Encryption",
  "Network Security Best Practices",
],

};

export default questionBanks;